# Tratamento/Limpeza dos dados

## Bibliotecas

In [32]:
import pandas as pd

## Importação do csv

In [33]:
df = pd.read_csv('combined_data.csv')

C:\Users\duike\AppData\Local\Temp\ipykernel_15288\997897169.py:1: DtypeWarning: Columns (84,87,88,97,98,99,100,101,102) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('combined_data.csv')

## Visualização dos dados

In [34]:
numero_linhas = len(df)
print(f"Número de linhas: {numero_linhas}")

Número de linhas: 3570342

In [35]:
df.describe()

,UF_ZI,ANO_CMPT,MES_CMPT,ESPEC,CGC_HOSP,N_AIH,IDENT,CEP,MUNIC_RES,NASC,SEXO,UTI_MES_IN,UTI_MES_AN,UTI_MES_AL,UTI_MES_TO,MARCA_UTI,UTI_INT_IN,UTI_INT_AN,UTI_INT_AL,UTI_INT_TO,DIAR_ACOM,QT_DIARIAS,PROC_SOLIC,PROC_REA,VAL_SH,VAL_SP,VAL_SADT,VAL_RN,VAL_ACOMP,VAL_ORTP,VAL_SANGUE,VAL_SADTSR,VAL_TRANSP,VAL_OBSANG,VAL_PED1AC,VAL_TOT,VAL_UTI,US_TOT,DT_INTER,DT_SAIDA,DIAG_SECUN,COBRANCA,NATUREZA,NAT_JUR,GESTAO,RUBRICA,IND_VDRL,MUNIC_MOV,COD_IDADE,IDADE,DIAS_PERM,MORTE,NACIONAL,NUM_PROC,CAR_INT,TOT_PT_SP,CPF_AUT,HOMONIMO,NUM_FILHOS,INSTRU,CONTRACEP1,CONTRACEP2,GESTRISCO,INSC_PN,SEQ_AIH5,CBOR,CNAER,VINCPREV,GESTOR_COD,GESTOR_TP,GESTOR_CPF,GESTOR_DT,CNES,CNPJ_MANT,INFEHOSP,CID_ASSO,CID_MORTE,COMPLEX,FINANC,FAEC_TP,REGCT,RACA_COR,SEQUENCIA,VAL_SH_FED,VAL_SP_FED,VAL_SH_GES,VAL_SP_GES,VAL_UCI,MARCA_UCI,DIAGSEC9,TPDISEC1,TPDISEC2,TPDISEC3,TPDISEC4,TPDISEC5,TPDISEC6,TPDISEC7,TPDISEC8,TPDISEC9
count,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,2.562966e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3570342.0,3570342.0,3570342.0,3.570342e+06,3.570342e+06,3570342.0,3570342.0,3570342.0,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3570342.0,3570342.0,3570342.0,3570342.0,3570342.0,3570342.0,3570342.0,3570342.0,3570342.0,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3570342.0,3.570342e+06,3570342.0,3.570342e+06,3.570342e+06,3570342.0,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,0.0,3.570342e+06,3570342.0,0.0,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3570342.0,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,0.0,3.570342e+06,2.389507e+06,0.0,3570342.0,3570342.0,3.570342e+06,3.570342e+06,130756.000000,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,0.0,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3.570342e+06,3570342.0
mean,2.602413e+05,2.021583e+03,6.623184e+00,2.978861e+00,1.156819e+13,2.622289e+12,1.029885e+00,5.442888e+07,2.614788e+05,1.980342e+07,2.166545e+00,0.0,0.0,0.0,5.833996e-01,5.483446e+00,0.0,0.0,0.0,6.710338e-02,3.027197e+00,4.939238e+00,3.471284e+08,3.472279e+08,1.323680e+03,3.331380e+02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.671011e+03,4.333727e+02,3.330615e+02,2.021600e+07,2.021624e+07,0.0,2.341923e+01,0.0,1.867935e+03,1.724615e+00,0.0,1.208304e-01,2.609694e+05,3.896964e+00,4.092702e+01,5.380950e+00,4.870150e-02,1.002960e+01,NaN,1.775507e+00,0.0,NaN,9.741364e-04,3.356653e-02,3.405388e-02,1.125063e-01,8.032704e-02,9.966838e-01,5.206966e+07,0.0,1.992274e-01,3.977210e-05,1.400426e-06,1.289021e+00,2.435991e-01,7.989419e+09,NaN,2.251513e+06,1.104066e+13,NaN,0.0,0.0,2.096387e+00,5.926705e+00,40061.283704,1.247945e+03,2.068941e+01,1.519943e+04,8.978708e+00,4.829811e+00,3.657291e-01,1.844117e-02,1.224110e+01,1.357573e-02,NaN,2.872456e-01,5.426903e-02,2.267906e-02,9.060757e-03,3.006155e-03,8.635027e-04,1.845762e-04,8.402556e-07,0.0
std,4.482746e+02,1.748531e+00,3.425892e+00,4.712110e+00,4.365103e+12,6.704198e+10,3.444521e-01,2.720435e+06,8.424914e+03,2.498973e+05,9.860339e-01,0.0,0.0,0.0,3.025728e+00,1.943082e+01,0.0,0.0,0.0,1.014968e+00,5.162340e+00,6.367636e+00,5.438716e+07,5.441639e+07,3.489563e+03,8.420695e+02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.179476e+03,2.579082e+03,8.324849e+02,1.797382e+04,1.755308e+04,0.0,1.770969e+01,0.0,1.248054e+03,4.467083e-01,0.0,3.259302e-01,3.616200e+02,4.209685e-01,2.455543e+01,6.985823e+00,2.152433e-01,1.698301e+00,NaN,5.061473e-01,0.0,NaN,4.412850e-02,3.237134e-01,3.050655e-01,9.920929e-01,8.668070e-01,5.749098e-02,3.662048e+09,0.0,3.764471e+02,7.515077e-02,2.646154e-03,1.035492e+01,4.292536e-01,1.712214e+10,NaN,2.341900e+06,2.986446e+12,NaN,0.0,0.0,2.951218e-01,3.757909e-01,22.577167,2.703113e+03,3.743461e+01,1.328150e+04,8.343855e+01,4.175930e+01,1.510807e+01,2.176663e+00,1.853306e+02,1.636582e-01,NaN,5.257546e-01,2.436876e-01,1.614298e-01,1.036548e-01,6.025505e-02,3.266833e-02,1.516298e-02,1.183396e-03,0.0
min,2.600000e+05,2.019000e+03,1.000000e+00,1.000000e+00,2.288130e+11,2.608100e+12,1.000000e+00,1.001000e+06,1.100010e+05,1.893072e+07,1.000000e+00,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,2.010100e+08,2.010100e+08,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,2.008010e+07,2.018100e+07,0.0,1.100000e+01,0.0,1.023000e+03,1.000000e+00,0.0,0.000000e+00,2.600050e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+01,NaN,1.000000e+00,0.0,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,3.500000e+01,1.596018e+12,NaN,0.0,0.0,2.000000e+00,4.000000e+00,40024.000000,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
25%,2.600000e+05,2.020000e+03,4.000000e+00,1.000000e+00,1.057205e+13,2.620104e+12,1.000000e+00,5.340174e+07,2.605200e+05,1.960052e+07,1.000000e+00,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.000000e+00,1.000000e+00,3.030801e+08,3.030801e+08,2.766000e+02,5.716000e+01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.767800e+02,0.000000e+00,7.650000e+01,2.020062e+07,2.020070e+07,0.0,1.200000e+01,0.0,1.023000e+03,1.000000e+00,0.0,0.000000e+00,2.607900e+05,4.000000e+00,2.200000e+01,1.000000e+00,0.000000e+00,1.000000e+01,NaN,2.000000e+00,0.0,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,6.550000e+02,1.057205e+13,NaN,0.0,0.0,2.000000e+00,6.000000e+00,40032.000000,0.000000e+00,3.000000e+00,2.570000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
50%,2.600000e+05,2.022000e+03,7.000000e+00,3.000000e+00,1.057205e+13,2.622101e+12,1.000000e+00,5.517000e+07,2.609600e+05,1.982111e+07,3.000000e+00,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000e+00,1.000000e+00,3.000000e+00,3.080100e+08,3.080100e+08,4.674700e+02,1.462100e+02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.588800e+02,0.000000e+00,1.326300e+02,2.022022e+07,2.022022e+07,0.0,1.200000e+01,0.0,1.147000e+03,2.000000e+00,0.0,0.000000e+00,2.611600e+05,4.000000e+00,3.900000e+01,3.000000e+00,0.000000e+00,1.000000e+01,NaN,2.000000e+00,0.0,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,2.427427e+06,1.057205e+13,NaN,0.0,0.0,2.000000e+00,6.000000e+00,40080.000000,0.000000e+00,3.000000e+00,1.244250e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
75%,2.601800e+05,2.023000e+03,1.000000e+01,3.000000e+00,1.098830e+13,2.623106e+12,1.000000e+00,5.580097e+07,2.611600e+05,1.999072e+07,3.000000e+00,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000e+00,4.000000e+00,6.000000e+00,4.080603e+08,4.080604e+08,9.857900e+02,3.040100e+02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.268140e+03,0.000000e+00,2.583500e+02,2.023081e+07,2.023082e+07,0.0,3.100000e+01,0.0,3.069000e+03,2.000000e+00,0.0,0.000000e+00,2.611600e+05,4.000000e+00,6.100000e+01,7.000000e+00,0.000000e+00,1.000000e+01,NaN,2.000000e+00,0.0,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,2.712016e+06,1.057205e+13,NaN,0.0,0.0,2.000000e+00,6.000000e+00,40080.000000,0.000000e+00,3.000000e+00,2.555400e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
max,2.616500e+05,2.024000e+03,1.200000e+01,8.700000e+01,7.023723e+13,9.924300e+12,5.000000e+00,9.999000e+07,5.300100e+05,2.024123e+07,3.000000e+00,0.0,0.0,0.0,1.670000e+02,9.900000e+01,0.0,0.0,0.0,9.000000e+01,1.980000e+02,3.420000e+02,5.060201e+08,5.060201e+08,2.322648e+05,4.195050e+04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.705682e+05,2.672000e+05,5.223324e+04,2.024123e+07,2.024123e+07,0.0,6.700000e+01,0.0,3.999000e+03,2.000000e+00,0.0,1.000000e+00,2.616500e+05,5.000000e+00,9.900000e+01,3.420000e+02,1.000000e+00,3.500000e+02,NaN,6.000000e+00,0.0,NaN,2.000000e+00,7.300000e+01,4.000000e+00,1.300000e+01,1.300000e+01,1.000000e+00,7.050015e+11,0.0,7.113100e+05,1.420000e+02,5.000000e+00,2.070000e+02,1.000000e+00,9.986270e+10,NaN,9.994289e+06,4.089378e+13,NaN,0.0,0.0,3.000000e+00,6.000000e+00,40083.000000,7.109000e+03,9.900000e+01,5.975800e+04,4.891460e+03,2.245990e+03,1.093110e+03,3.706000e+02,1.755000e+04,3.000000e+00,NaN,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,0.0

In [46]:
df.head(20)

,UF_ZI,ANO_CMPT,MES_CMPT,ESPEC,CGC_HOSP,N_AIH,IDENT,CEP,MUNIC_RES,NASC,SEXO,UTI_MES_IN,UTI_MES_AN,UTI_MES_AL,UTI_MES_TO,MARCA_UTI,UTI_INT_IN,UTI_INT_AN,UTI_INT_AL,UTI_INT_TO,DIAR_ACOM,QT_DIARIAS,PROC_SOLIC,PROC_REA,VAL_SH,VAL_SP,VAL_SADT,VAL_RN,VAL_ACOMP,VAL_ORTP,VAL_SANGUE,VAL_SADTSR,VAL_TRANSP,VAL_OBSANG,VAL_PED1AC,VAL_TOT,VAL_UTI,US_TOT,DT_INTER,DT_SAIDA,DIAG_PRINC,DIAG_SECUN,COBRANCA,NATUREZA,NAT_JUR,GESTAO,RUBRICA,IND_VDRL,MUNIC_MOV,COD_IDADE,IDADE,DIAS_PERM,MORTE,NACIONAL,NUM_PROC,CAR_INT,TOT_PT_SP,CPF_AUT,HOMONIMO,NUM_FILHOS,INSTRU,CID_NOTIF,CONTRACEP1,CONTRACEP2,GESTRISCO,INSC_PN,SEQ_AIH5,CBOR,CNAER,VINCPREV,GESTOR_COD,GESTOR_TP,GESTOR_CPF,GESTOR_DT,CNES,CNPJ_MANT,INFEHOSP,CID_ASSO,CID_MORTE,COMPLEX,FINANC,FAEC_TP,REGCT,RACA_COR,ETNIA,SEQUENCIA,REMESSA,AUD_JUST,SIS_JUST,VAL_SH_FED,VAL_SP_FED,VAL_SH_GES,VAL_SP_GES,VAL_UCI,MARCA_UCI,DIAGSEC1,DIAGSEC2,DIAGSEC3,DIAGSEC4,DIAGSEC5,DIAGSEC6,DIAGSEC7,DIAGSEC8,DIAGSEC9,TPDISEC1,TPDISEC2,TPDISEC3,TPDISEC4,TPDISEC5,TPDISEC6,TPDISEC7,TPDISEC8,TPDISEC9
0,260000,2019,1,1,3.544600e+13,2619104343889,1,56480000,261480,19450305,1,0,0,0,0,0,0,0,0,0,2,2,407040129,407040129,314.55,136.44,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,450.99,0.0,120.90,20181229,20181231,K429,0,11,0,3999,2,0,0,261100,4,73,2,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,0,0,NaN,7152566,NaN,NaN,0,0,2,6,NaN,0,3,0,7426,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0
1,260000,2019,1,1,3.544600e+13,2619104343890,1,56480000,261480,19580319,1,0,0,0,0,0,0,0,0,0,0,2,407020284,407020284,191.10,124.84,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,315.94,0.0,84.70,20190105,20190107,I842,0,11,0,3999,2,0,0,261100,4,60,2,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,0,0,NaN,7152566,NaN,NaN,0,0,2,6,NaN,0,3,0,7427,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0
2,260000,2019,1,1,3.544600e+13,2619104343900,1,56460000,261100,20160504,1,0,0,0,0,0,0,0,0,0,1,1,409050032,409050032,232.34,148.62,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,380.96,0.0,102.13,20181220,20181221,Q541,0,11,0,3999,2,0,0,261100,4,2,1,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,0,0,NaN,7152566,NaN,NaN,0,0,2,6,NaN,0,3,0,7428,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0
3,260000,2019,1,1,3.544600e+13,2619104343911,1,56460000,261100,20090112,1,0,0,0,0,0,0,0,0,0,1,1,401020150,401020150,230.32,121.30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,351.62,0.0,94.26,20181220,20181221,Q181,0,11,0,3999,2,0,0,261100,4,9,1,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,0,0,NaN,7152566,NaN,NaN,0,0,2,6,NaN,0,3,0,7429,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0
4,260000,2019,1,1,3.544600e+13,2619104343922,1,56460000,261100,20161210,3,0,0,0,0,0,0,0,0,0,2,2,407040129,407040129,314.55,136.44,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,450.99,0.0,120.90,20181220,20181222,K429,0,11,0,3999,2,0,0,261100,4,2,2,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,0,0,NaN,7152566,NaN,NaN,0,0,2,6,NaN,0,3,0,7430,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0
5,260000,2019,1,1,3.544600e+13,2619104343933,1,56580000,260660,19940402,1,0,0,0,0,0,0,0,0,0,0,1,409050083,409050083,97.72,121.40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,219.12,0.0,58.74,20181231,20190101,N47,0,11,0,3999,2,0,0,261100,4,24,1,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,0,0,NaN,7152566,NaN,NaN,0,0,2,6,NaN,0,3,0,7431,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0
6,260000,2019,1,1,3.544600e+13,2619104343944,1,56395000,260875,20080420,1,0,0,0,0,0,0,0,0,0,1,1,409050083,409050083,105.72,121.40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,227.12,0.0,60.89,20181125,20181126,N47,0,11,0,3999,2,0,0,261100,4,10,1,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,0,0,NaN,7152566,NaN,NaN,0,0,2,6,NaN,0,3,0,7432,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0
7,260000,2019,1,3,3.544600e+13,2619104344186,1,56460000,261100,19200110,3,0,0,0,0,0,0,0,0,0,3,3,303140151,303140151,528.07,78.35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,606.42,0.0,162.57,20181218,20181221,J180,0,11,0,3999,2,0,0,261100,4,98,3,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,0,0,NaN,7152566,NaN,NaN,0,0,2,6,NaN,0,3,0,7525,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0
8,260000,2019,1,3,3.544600e+13,2619104344197,1,56460000,261100,19470125,1,0,0,0,0,0,0,0,0,0,0,2,303060182,303060182,134.29,38.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,172.34,0.0,46.20,20181219,20181221,I159,0,11,0,3999,2,0,0,261100,4,71,2,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,0,0,NaN,7152566,NaN,NaN,0,0,2,6,NaN,0,3,0,7526,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0
9,260000,2019,1,3,3.544600e+13,2619104344208,1,56420000,260392,19450819,1,0,0,0,0,0,0,0,0,0,0,4,303150017,303150017,53.10,14.21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67.31,0.0,18.04,20190103,20190107,N410,0,11,0,3999,2,0,0,261100,4,73,4,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,1,31134424434,NaN,7152566,NaN,NaN,0,0,2,6,NaN,0,3,0,7527,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0
10,260000,2019,1,3,3.544600e+13,2619104344219,1,56460000,261100,19780126,3,0,0,0,0,0,0,0,0,0,0,3,303150041,303150041,294.28,53.67,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,347.95,0.0,93.28,20190102,20190105,N10,0,11,0,3999,2,0,0,261100,4,40,3,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,1,39795365487,NaN,7152566,NaN,NaN,0,0,2,6,NaN,0,3,0,7528,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0
11,260000,2019,1,3,3.544600e+13,2619104344220,1,56460000,261100,19860606,3,0,0,0,0,0,0,0,0,0,0,4,303150033,303150033,171.65,27.16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,198.81,0.0,53.30,20190108,20190112,N739,0,11,0,3999,2,0,0,261100,4,32,4,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,0,0,NaN,7152566,NaN,NaN,0,0,2,6,NaN,0,3,0,7529,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0
12,260000,2019,1,3,3.544600e+13,2619104344230,1,56460000,261100,19840305,3,0,0,0,0,0,0,0,0,0,0,4,308040015,308040015,170.12,29.21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,199.33,0.0,53.43,20181207,20181211,T814,0,11,0,3999,2,0,0,261100,4,34,4,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,0,0,NaN,7152566,NaN,NaN,0,0,2,6,NaN,0,3,0,7530,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,Y899,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0,0,0,0
13,260000,2019,1,3,3.544600e+13,2619104344241,1,56580000,260660,19480415,1,0,0,0,0,0,0,0,0,0,7,7,303150017,303150017,109.10,14.21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,123.31,0.0,33.05,20181210,20181217,N410,0,11,0,3999,2,0,0,261100,4,70,7,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,0,0,NaN,7152566,NaN,NaN,0,0,2,6,NaN,0,3,0,7531,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0
14,260000,2019,1,3,NaN,2618104079228,1,55680000,260230,19430516,1,0,0,0,0,0,0,0,0,0,0,6,303140135,303140135,451.47,29.40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,480.87,0.0,128.91,20181104,20181110,J159,0,12,0,1023,2,0,0,260410,4,75,6,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,0,0,NaN,2428989,1.057205e+13,NaN,0,0,2,6,NaN,0,99,0,5855,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0
15,260000,2019,1,3,NaN,2618104079239,1,56550970,260750,19190114,3,0,0,0,0,0,0,0,0,0,0,10,303140135,303140135,451.47,29.40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,480.87,0.0,128.91,20181101,20181111,J189,0,12,0,1023,2,0,0,260410,4,99,10,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,0,0,NaN,2428989,1.057205e+13,NaN,0,0,2,6,NaN,0,3,0,5856,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0
16,260000,2019,1,3,NaN,2618104079240,1,55099899,260410,20010713,1,0,0,0,0,0,0,0,0,0,0,2,303020032,303020032,373.76,39.65,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,413.41,0.0,110.83,20181110,20181111,D649,0,31,0,1023,2,0,0,260410,4,17,1,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,0,0,NaN,2428989,1.057205e+13,NaN,0,0,2,6,NaN,0,3,0,5857,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0
17,260000,2019,1,3,NaN,2618104079261,1,55260000,260060,19340113,1,0,0,0,0,0,0,0,0,0,0,7,303040165,303040165,85.31,27.52,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,112.83,0.0,30.24,20181106,20181113,G009,0,12,0,1023,2,0,0,260410,4,84,7,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,0,0,NaN,2428989,1.057205e+13,NaN,0,0,2,6,NaN,0,3,0,5859,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0
18,260000,2019,1,3,NaN,2618104079272,1,55021260,260410,20000218,1,0,0,0,0,0,0,0,0,0,0,8,303030038,303030038,310.79,50.01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,360.80,0.0,96.72,20181105,20181113,E110,0,12,0,1023,2,0,0,260410,4,18,8,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,1,31134424434,NaN,2428989,1.057205e+13,NaN,0,0,2,6,NaN,0,3,0,5860,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0
19,260000,2019,1,1,1.057205e+13,2619104308161,1,55240000,261120,20000404,1,0,0,0,0,0,0,0,0,0,4,4,412040166,412040166,669.86,404.28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1074.14,0.0,287.97,20181230,20190103,S272,0,12,0,1023,2,0,0,260120,4,18,4,0,10,NaN,2,0,NaN,0,0,0,NaN,0,0,1,0,0,0,0,0,0,0,0,NaN,2551764,1.057205e+13,NaN,0,0,2,6,NaN,0,1,0,5966,HE26000001N201901.DTS,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,Y899,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0,0,0,0

In [62]:
df['CONTRACEP1'].value_counts()

CONTRACEP1
0     3523389
8       28948
10      11893
11       1934
12       1390
6         996
1         821
7         595
9         151
4         111
2          65
3          21
13         15
5          13
Name: count, dtype: int64

In [47]:
# Verificando colunas com valores 0
# UTI_MES_IN	UTI_MES_AN	UTI_MES_AL	UTI_MES_TO	MARCA_UTI	UTI_INT_IN	UTI_INT_AN	UTI_INT_AL	UTI_INT_TO
colunas_com_zeros = (df == 0).sum()
colunas_com_zeros = colunas_com_zeros[colunas_com_zeros > 0]
colunas_com_zeros

UTI_MES_IN    3570342
UTI_MES_AN    3570342
UTI_MES_AL    3570342
UTI_MES_TO    3301288
MARCA_UTI     3301288
               ...
TPDISEC5      3560740
TPDISEC6      3567624
TPDISEC7      3569764
TPDISEC8      3570340
TPDISEC9      3570342
Length: 67, dtype: int64

## Tratamento dos nulos

In [39]:
null_counts = df.isnull().sum()
colunas_com_nulos = null_counts[null_counts > 0]

print(colunas_com_nulos)

CGC_HOSP     1007376
NUM_PROC     3570342
CPF_AUT      3570342
CID_NOTIF    3523392
GESTOR_DT    3570342
CNPJ_MANT    1180835
INFEHOSP     3570342
FAEC_TP      3439586
AUD_JUST     3549111
SIS_JUST     3550231
DIAGSEC1     2672742
DIAGSEC2     3390971
DIAGSEC3     3496323
DIAGSEC4     3541144
DIAGSEC5     3560740
DIAGSEC6     3567624
DIAGSEC7     3569764
DIAGSEC8     3570340
DIAGSEC9     3570342
dtype: int64

In [48]:
threshold_para_remover_nulos = numero_linhas * 0.7
lista_colunas_para_remover = colunas_com_nulos[colunas_com_nulos > threshold_para_remover_nulos].index
lista_colunas_para_remover = lista_colunas_para_remover.union(colunas_com_zeros[colunas_com_zeros > threshold_para_remover_nulos].index)
lista_colunas_para_remover

Index(['AUD_JUST', 'CBOR', 'CID_ASSO', 'CID_MORTE', 'CID_NOTIF', 'CNAER',
       'CONTRACEP1', 'CONTRACEP2', 'CPF_AUT', 'DIAGSEC1', 'DIAGSEC2',
       'DIAGSEC3', 'DIAGSEC4', 'DIAGSEC5', 'DIAGSEC6', 'DIAGSEC7', 'DIAGSEC8',
       'DIAGSEC9', 'DIAG_SECUN', 'ETNIA', 'FAEC_TP', 'GESTOR_COD',
       'GESTOR_CPF', 'GESTOR_DT', 'GESTOR_TP', 'HOMONIMO', 'IND_VDRL',
       'INFEHOSP', 'INSC_PN', 'INSTRU', 'MARCA_UCI', 'MARCA_UTI', 'MORTE',
       'NATUREZA', 'NUM_FILHOS', 'NUM_PROC', 'REGCT', 'RUBRICA', 'SEQ_AIH5',
       'SIS_JUST', 'TOT_PT_SP', 'TPDISEC1', 'TPDISEC2', 'TPDISEC3', 'TPDISEC4',
       'TPDISEC5', 'TPDISEC6', 'TPDISEC7', 'TPDISEC8', 'TPDISEC9',
       'UTI_INT_AL', 'UTI_INT_AN', 'UTI_INT_IN', 'UTI_INT_TO', 'UTI_MES_AL',
       'UTI_MES_AN', 'UTI_MES_IN', 'UTI_MES_TO', 'VAL_ACOMP', 'VAL_OBSANG',
       'VAL_ORTP', 'VAL_PED1AC', 'VAL_RN', 'VAL_SADT', 'VAL_SADTSR',
       'VAL_SANGUE', 'VAL_SH_FED', 'VAL_SH_GES', 'VAL_SP_FED', 'VAL_SP_GES',
       'VAL_TRANSP', 'VAL_UCI', 'VAL_UTI', 'VINCPREV'],
      dtype='object')

In [49]:
df_cleaned = df.drop(columns=lista_colunas_para_remover)

In [51]:
# quantidade de colunas
print(f"Número de colunas após remoção: {len(df_cleaned.columns)}")

Número de colunas após remoção: 39

In [56]:
#veja os valores da coluna COD_IDADE se existem valores diferentes de 4
df_cleaned['NACIONAL'].value_counts()

NACIONAL
10     3568561
81         472
30         159
45         107
103         97
        ...
274          1
178          1
130          1
95           1
43           1
Name: count, Length: 67, dtype: int64

In [54]:
df_cleaned.head(20)

,UF_ZI,ANO_CMPT,MES_CMPT,ESPEC,CGC_HOSP,N_AIH,IDENT,CEP,MUNIC_RES,NASC,SEXO,DIAR_ACOM,QT_DIARIAS,PROC_SOLIC,PROC_REA,VAL_SH,VAL_SP,VAL_TOT,US_TOT,DT_INTER,DT_SAIDA,DIAG_PRINC,COBRANCA,NAT_JUR,GESTAO,MUNIC_MOV,COD_IDADE,IDADE,DIAS_PERM,NACIONAL,CAR_INT,GESTRISCO,CNES,CNPJ_MANT,COMPLEX,FINANC,RACA_COR,SEQUENCIA,REMESSA
0,260000,2019,1,1,3.544600e+13,2619104343889,1,56480000,261480,19450305,1,2,2,407040129,407040129,314.55,136.44,450.99,120.90,20181229,20181231,K429,11,3999,2,261100,4,73,2,10,2,1,7152566,NaN,2,6,3,7426,HE26000001N201901.DTS
1,260000,2019,1,1,3.544600e+13,2619104343890,1,56480000,261480,19580319,1,0,2,407020284,407020284,191.10,124.84,315.94,84.70,20190105,20190107,I842,11,3999,2,261100,4,60,2,10,2,1,7152566,NaN,2,6,3,7427,HE26000001N201901.DTS
2,260000,2019,1,1,3.544600e+13,2619104343900,1,56460000,261100,20160504,1,1,1,409050032,409050032,232.34,148.62,380.96,102.13,20181220,20181221,Q541,11,3999,2,261100,4,2,1,10,2,1,7152566,NaN,2,6,3,7428,HE26000001N201901.DTS
3,260000,2019,1,1,3.544600e+13,2619104343911,1,56460000,261100,20090112,1,1,1,401020150,401020150,230.32,121.30,351.62,94.26,20181220,20181221,Q181,11,3999,2,261100,4,9,1,10,2,1,7152566,NaN,2,6,3,7429,HE26000001N201901.DTS
4,260000,2019,1,1,3.544600e+13,2619104343922,1,56460000,261100,20161210,3,2,2,407040129,407040129,314.55,136.44,450.99,120.90,20181220,20181222,K429,11,3999,2,261100,4,2,2,10,2,1,7152566,NaN,2,6,3,7430,HE26000001N201901.DTS
5,260000,2019,1,1,3.544600e+13,2619104343933,1,56580000,260660,19940402,1,0,1,409050083,409050083,97.72,121.40,219.12,58.74,20181231,20190101,N47,11,3999,2,261100,4,24,1,10,2,1,7152566,NaN,2,6,3,7431,HE26000001N201901.DTS
6,260000,2019,1,1,3.544600e+13,2619104343944,1,56395000,260875,20080420,1,1,1,409050083,409050083,105.72,121.40,227.12,60.89,20181125,20181126,N47,11,3999,2,261100,4,10,1,10,2,1,7152566,NaN,2,6,3,7432,HE26000001N201901.DTS
7,260000,2019,1,3,3.544600e+13,2619104344186,1,56460000,261100,19200110,3,3,3,303140151,303140151,528.07,78.35,606.42,162.57,20181218,20181221,J180,11,3999,2,261100,4,98,3,10,2,1,7152566,NaN,2,6,3,7525,HE26000001N201901.DTS
8,260000,2019,1,3,3.544600e+13,2619104344197,1,56460000,261100,19470125,1,0,2,303060182,303060182,134.29,38.05,172.34,46.20,20181219,20181221,I159,11,3999,2,261100,4,71,2,10,2,1,7152566,NaN,2,6,3,7526,HE26000001N201901.DTS
9,260000,2019,1,3,3.544600e+13,2619104344208,1,56420000,260392,19450819,1,0,4,303150017,303150017,53.10,14.21,67.31,18.04,20190103,20190107,N410,11,3999,2,261100,4,73,4,10,2,1,7152566,NaN,2,6,3,7527,HE26000001N201901.DTS
10,260000,2019,1,3,3.544600e+13,2619104344219,1,56460000,261100,19780126,3,0,3,303150041,303150041,294.28,53.67,347.95,93.28,20190102,20190105,N10,11,3999,2,261100,4,40,3,10,2,1,7152566,NaN,2,6,3,7528,HE26000001N201901.DTS
11,260000,2019,1,3,3.544600e+13,2619104344220,1,56460000,261100,19860606,3,0,4,303150033,303150033,171.65,27.16,198.81,53.30,20190108,20190112,N739,11,3999,2,261100,4,32,4,10,2,1,7152566,NaN,2,6,3,7529,HE26000001N201901.DTS
12,260000,2019,1,3,3.544600e+13,2619104344230,1,56460000,261100,19840305,3,0,4,308040015,308040015,170.12,29.21,199.33,53.43,20181207,20181211,T814,11,3999,2,261100,4,34,4,10,2,1,7152566,NaN,2,6,3,7530,HE26000001N201901.DTS
13,260000,2019,1,3,3.544600e+13,2619104344241,1,56580000,260660,19480415,1,7,7,303150017,303150017,109.10,14.21,123.31,33.05,20181210,20181217,N410,11,3999,2,261100,4,70,7,10,2,1,7152566,NaN,2,6,3,7531,HE26000001N201901.DTS
14,260000,2019,1,3,NaN,2618104079228,1,55680000,260230,19430516,1,0,6,303140135,303140135,451.47,29.40,480.87,128.91,20181104,20181110,J159,12,1023,2,260410,4,75,6,10,2,1,2428989,1.057205e+13,2,6,99,5855,HE26000001N201901.DTS
15,260000,2019,1,3,NaN,2618104079239,1,56550970,260750,19190114,3,0,10,303140135,303140135,451.47,29.40,480.87,128.91,20181101,20181111,J189,12,1023,2,260410,4,99,10,10,2,1,2428989,1.057205e+13,2,6,3,5856,HE26000001N201901.DTS
16,260000,2019,1,3,NaN,2618104079240,1,55099899,260410,20010713,1,0,2,303020032,303020032,373.76,39.65,413.41,110.83,20181110,20181111,D649,31,1023,2,260410,4,17,1,10,2,1,2428989,1.057205e+13,2,6,3,5857,HE26000001N201901.DTS
17,260000,2019,1,3,NaN,2618104079261,1,55260000,260060,19340113,1,0,7,303040165,303040165,85.31,27.52,112.83,30.24,20181106,20181113,G009,12,1023,2,260410,4,84,7,10,2,1,2428989,1.057205e+13,2,6,3,5859,HE26000001N201901.DTS
18,260000,2019,1,3,NaN,2618104079272,1,55021260,260410,20000218,1,0,8,303030038,303030038,310.79,50.01,360.80,96.72,20181105,20181113,E110,12,1023,2,260410,4,18,8,10,2,1,2428989,1.057205e+13,2,6,3,5860,HE26000001N201901.DTS
19,260000,2019,1,1,1.057205e+13,2619104308161,1,55240000,261120,20000404,1,4,4,412040166,412040166,669.86,404.28,1074.14,287.97,20181230,20190103,S272,12,1023,2,260120,4,18,4,10,2,1,2551764,1.057205e+13,2,6,1,5966,HE26000001N201901.DTS

In [63]:
df_cleaned.to_csv('cleaned_data.csv', index=False)